"""Add health fields to User model

Revision ID: 10bbc1ed3293
Revises: 
Create Date: 2025-04-27 22:20:00.591245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10bbc1ed3293'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allergies', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('medications', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_updated')
        batch_op.drop_column('emergency_contact')
        batch_op.drop_column('medications')
        batch_op.drop_column('allergies')

    # ### end Alembic commands ###
